name: Deploy Django application to hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

step:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Devloploy Via ssh
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      script: 
        cd Django-first/
        git pull